services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_SESSION_REQUEST_TIMEOUT=600
      - SE_NEW_SESSION_WAIT_TIMEOUT=600
    networks:
      - selenium-grid-kk-net

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_SESSION_REQUEST_TIMEOUT=600
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_VNC_NO_PASSWORD=1
      - SE_START_VNC=true
    ports:
      - "5900:5900"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - selenium-grid-kk-net

  firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_SESSION_REQUEST_TIMEOUT=600
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_VNC_NO_PASSWORD=1
      - SE_START_VNC=true
    ports:
      - "5901:5900"
      - "7901:7900"
    shm_size: 2gb
    networks:
      - selenium-grid-kk-net

networks:
  selenium-grid-kk-net:
    driver: bridge